spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: 1234
    url: jdbc:mysql://172.31.108.47:3306/fido?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: hgy
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update